### ISSUE TITLE
Creator stays on as admin

### ISSUE THREAD

**Issue by arirawr** [HackathonHackers/org#4]
This line disturbs me, given that the reason this structure came up was said creator's unilateral overruling of an existing system. There's nothing stopping that from happening again.

@rubinovitz

**Comment by rubinovitz** [comment]
"This is your community as much as it is ours." lol

**Comment by rubinovitz** [comment]
"There is only one active admin, though the creator of the group exists on the panel, only to ensure that no newly added admin ever reaches a point where they refuse to give up ownership of the group when their term has ended."

But @hellyeah is the one who needs to give up ownership...

**Comment by gauss1181** [comment]
@rubinovitz: "But @hellyeah is the one who needs to give up ownership..."

+1

**Comment by nsgomez** [comment]
+1

**Comment by brettneese** [comment]
+1

**Comment by gauss1181** [comment]
+1

**Comment by ghost** [comment]
+1

You either die a hero or live long enough to see yourself become Dave Fontenot.

**Comment by chen-ye** [comment]
+1

**Comment by haydenmc** [comment]
Agree. This needs to be addressed before this plan can be considered a solution.

**Comment by suspended** [comment]
+1. 

Nice smokescreen you threw there Hallie.

**Comment by sdaitzman** [comment]
The problem with this is that there's no mechanism for enforcement, but also no clear alternative path. If Dave is not the admin, who is?  What stops them from just deleting the group? On the other hand, what stops Dave from doing so?

The real solution is to put the group in the hands of a non-human well-tested system that will only allow potentially destructive actions approved by a majority of admins or whatever form of government is being put in place. This will not fly with Facebook. Anyone have an alternative?

**Comment by rubinovitz** [comment]
There are plenty of people more trustworthy at this point. E.G. Cassidy

**Comment by brettneese** [comment]
They can't delete the group unless they remove every single member of it by
hand.

**Comment by sdaitzman** [comment]
@rubinovitz I can't disagree.

@brettneese can't the owner of the group delete it?

**Comment by nsgomez** [comment]
@sdaitzman Removing 20,000 members by hand would be a pretty painstaking process to take on though.

**Comment by brettneese** [comment]
Nope. There's no "delete group" button.

On Sunday, December 13, 2015, Sam D notifications@github.com wrote:

> @rubinovitz https://github.com/rubinovitz I can't disagree.
> 
> @brettneese https://github.com/brettneese can't the owner of the group
> do so?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/HackathonHackers/org/issues/4#issuecomment-164326214.

## 

Brett Neese
563-210-3459

**Comment by sdaitzman** [comment]
Guess I'm wrong there. I'm still concerned about having one person in more control over the group than anyone else, no matter how trustworthy that person is.

**Comment by rubinovitz** [comment]
Alerts can also be setup to intervene if this as happening.

**Comment by rubinovitz** [comment]
There should be two trusted people with incentives aligned with the groups
success. Neither should hold absolute power over the other.

**Comment by brettneese** [comment]
And it does not have to be just one. We can form a committee whose only job
is to make sure no other sub moderator goes off the rails.

On Sunday, December 13, 2015, rubinovitz notifications@github.com wrote:

> Alerts can also be setup to intervene if this as happening.
> 
> On Sun, Dec 13, 2015, 9:38 PM Nelson Gomez <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> 
> > @sdaitzman https://github.com/sdaitzman Yes. Removing 20,000 members
> > by
> > hand would be a pretty painstaking process to take on though.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/HackathonHackers/org/issues/4#issuecomment-164326270
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/HackathonHackers/org/issues/4#issuecomment-164326494.

## 

Brett Neese
563-210-3459

**Comment by nsgomez** [comment]
The committee system was basically what we had before. A better solution would've been to have a committee of admins (i.e. retaining the previous admins in the interim and holding elections for this) decide on things like the Code of Conduct but not doing admin work themselves, and then having a team of moderators to enforce it. I don't know how we arrived at the point where having one head admin was considered a good solution.

**Comment by rubinovitz** [comment]
Yes there are many solutions better than one person with unbalanced power.

**Comment by rubinovitz** [comment]
I think the medium post thinks committees are too slow?

**Comment by sdaitzman** [comment]
@nsgomez agreed. Aside from Dave, do we actually know who contributed to this decision?

**Comment by rubinovitz** [comment]
But I think people on the team with communication issues make things too
slow.

**Comment by rubinovitz** [comment]
Hacker fund is a great example of committee based leadership and they're
doing great! Getting lots done!

**Comment by rubinovitz** [comment]
Hallie, that I know of.

**Comment by sdaitzman** [comment]
We need more transparency into this </understatement>

**Comment by rubinovitz** [comment]
Yeah. Ideally we'd keep a board structure and could trust the creator but I
think that doesn't make sense at this point.

I would've had no problem voting in a new board and having hierarchies of
modbot mods before this.

**Comment by rubinovitz** [comment]
I had asked for admin depreciation plans in the past but was shot down. Now
we have a utilitarian solution that solves none of the problems.

Cassidy has always been incredible to everyone so I had hoped she would be
given the resources to rebuild without the constraint of the possibility of
being removed by a higher power this document glosses over.

**Comment by rubinovitz** [comment]
This is too risk averse and will stagnate growth.

**Comment by sdaitzman** [comment]
@hellyeah @rhallie15 thoughts? Is what @rubinovitz saying not true?

**Comment by sdaitzman** [comment]
I think it's important that if these decisions aren't made in public, they're at least discussed openly.

**Comment by rubinovitz** [comment]
What am I saying that is being contested?

**Comment by rubinovitz** [comment]
Re who was involved: Dave + Hallie is what I know of as I've been left out
of many discussions. I could be wrong here re: left out of discussion.

I was PMed and about Cassidy becoming the only admin and had said something
along the lines of anything is better than this. Cassidy can rebuild. I was
not aware creator was also staying on.

**Comment by sdaitzman** [comment]
I agree with you that this plan is quite risk averse and that it prevents growth. I also think it makes it harder for the community to regain trust. I want to hear both sides of this.

**Comment by sdaitzman** [comment]
Specifically, I want to know why an arbitrary person chosen by the subgroup leaders would not be a better fit for the role Dave is currently stepping into.

**Comment by rubinovitz** [comment]
I agree. I was clarifying what I know and trying not to speak for anyone
else. Would love to heard more.

**Comment by robbyoconnor** [comment]
Kill it with fire.

**Comment by sdaitzman** [comment]
Robby, I'm assuming you mean the line that establishes a leader who stays on forever?

**Comment by sdaitzman** [comment]
Also: what exactly are the rules for what the creator can do? What happens when they violate these?

**Comment by brettneese** [comment]
There are none, and there's nothing we as a community can do to prevent the
group creator from having unlimited power over the group, it's admins, etc
because he cannot be removed unless he steps down.

Brett Neese
563-210-3459

**Comment by hallie** [comment]
The reason for this change has been explained in detail [here](https://www.facebook.com/groups/hackathonhackers/permalink/1162721457116671/).

**Comment by haydenmc** [comment]
Has a resolution been reached here?

**Comment by suspended** [comment]
What's the point of discourse when Hallie and Dave are going to accept only their line of reasoning as acceptable? See Hallie's Facebook post, and accept it.

**Comment by rubinovitz** [comment]
Login wall. Please add to github.

**Comment by suspended** [comment]
Hallie Lomax
19 hrs · San Francisco, CA

I'm sure a lot of people are getting tired of talking about this, but an opportunity just arose for me to explain a concept that not a lot of people seemed to know about before yesterday.

I was going through the my unread GitHub notifications just now, and saw that a couple of subgroups had tried to add themselves to the HH group repo a few weeks ago. I looked up one that I'd never seen before, and sent a request to join it. Which is when I noticed in the sidebar that the group had no admin (I assume the original admin removed himself), and the group had gone into "free fall," meaning that anyone could add themselves as admin, so long as they were the first person to click the button. And so I did. And now I'm the admin of a random group I just found.

That's the danger of having a group where no admin has creator status. If I were to add on another person as admin, they could remove me, and then remove themselves. And then the cycle would continue. IDK why Facebook lets this kind of thing happen. It really makes no sense, and isn't practical, whatsoever.

**Comment by rubinovitz** [comment]
The chances of that vs current dictatorship is a no brainer for me, but
I've been saying that for a while and it doesn't seem to sink in.

**Comment by haydenmc** [comment]
I understand that an example underlining the reason for preserving the "creator" has been made, but a consensus wasn't clearly reached. I think marking this issue "closed" is premature.

**Comment by brettneese** [comment]
While after thinking about this I agree that for right now the creator should stay on as superadmin, I agree that consensus wasn't clearly reached -- there isn't even a process for reaching consensus currently -- and this should be re-opened.

**Comment by brettneese** [comment]
That being said, once we remove creator we can never bring them back and keeping the creator on in the meantime opens the possibility for Facebook to allow us to reassign that role.

**Comment by sdaitzman** [comment]
I don't think this has been resolved. I've opened PR #11 to clarify that the creator does not have authority to do _anything_ except for ensure power transitions happen. For technical reasons as explained by @rhallie15, this may be the closest to a good solution.

**Comment by haydenmc** [comment]
PR #11 adds clarity to the idea of having the creator stay on board, but that idea still hasn't reached consensus.

**Comment by sdaitzman** [comment]
@haydenmc I don't think that the creator should stay on board, but if for technical reasons they need to I believe we should have a very hard line around what they're permitted to do.

**Comment by rubinovitz** [comment]
Also actions that will be taken if they act outside of those permitted
actions

**Comment by hallie** [comment]
Clarification merged

**Comment by sdaitzman** [comment]
What actions could be taken?

**Comment by rubinovitz** [comment]
I really don't know.

That's my issue. This measure acts like we're preventing the group from
tail diving into chaos, when the group is already there, no matter how many
medium posts are written. Someone has already taken control of the group
and broken the rules, and there are no consequences to rectify it.

**Comment by nsgomez** [comment]
One thing that Daniel Eckert suggested in Hackers is incorporating a nonprofit organization to manage the group so that there'd be legal structures for elections and governance, and this is what many open-source projects do as well. However, my understanding is that this would also require replacing the single-admin structure with a board of directors (which would have certain legal authorities as a nonprofit board).

I still don't think this issue is quite resolved.

**Comment by rubinovitz** [comment]
+1. Would be down to have Hacker Fund take over while Hack Coop is
incorporated.

**Comment by rubinovitz** [comment]
Are @arirawr and @cassidoo still on HF board? if @cassidoo is no longer, can she be given a special position for this cause?

**Comment by rubinovitz** [comment]
(Hack Coop/Hack Co-Op context: a bunch of people in the HH community have
been discussing doing a Hacker cooperative. I'm finally filing the bylaws
this month, but it will take time. Hacker Fund is a great holding org for
now who I'd love to have move us forward if they're willing.

**Comment by rubinovitz** [comment]
Finally, I can't think of any arguments why arranging an at least temporary
transfer of power (probably with a future partnership promised) to Hacker
Fund, is not the BEST move/compromise here for the community.

Many [now-ex] HH admins have worked successfully with HF in the past and I think many would be willing to help them however they could to make the transfer go well.

**Comment by brettneese** [comment]
Incorporation as our own entity alone shouldn't be too expensive/difficult.
Hard part is applying for 501(c)3 which I don't think is too necessary tbh.

On Thursday, December 17, 2015, rubinovitz notifications@github.com wrote:

> (Hack Coop/Hack Co-Op context: a bunch of people in the HH community have
> been discussing doing a Hacker cooperative. I'm finally filing the bylaws
> this month, but it will take time. Hacker Fund is a great holding org for
> now who I'd love to have move us forward if they're willing.
> 
> On Thu, Dec 17, 2015 at 4:10 PM, JB Rubinovitz <jrubinovitz@gmail.com
> <javascript:_e(%7B%7D,'cvml','jrubinovitz@gmail.com');>>
> wrote:
> 
> > +1. Would be down to have Hacker Fund take over while Hack Coop is
> > incorporated.
> > 
> > On Thu, Dec 17, 2015 at 4:10 PM, Nelson Gomez <notifications@github.com
> > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> > wrote:
> > 
> > > One thing that Daniel Eckert suggested in Hackers is incorporating a
> > > nonprofit organization to manage the group so that there'd be legal
> > > structures for elections and governance, and this is what many
> > > open-source
> > > projects do as well. However, my understanding is that this would also
> > > require replacing the single-admin structure with a board of directors
> > > (which would have certain legal authorities as a nonprofit board).
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > > https://github.com/HackathonHackers/org/issues/4#issuecomment-165582878>
> > > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/HackathonHackers/org/issues/4#issuecomment-165584406.

## 

Brett Neese
563-210-3459

**Comment by rubinovitz** [comment]
I believe it took Justin a while. I sent him this thread for thoughts. I
think it takes on avg 2-12 months and some capital. I think we definitely
need a new interim structure and would love if HF could help with that +
partner with the new org.

**Comment by rubinovitz** [comment]
I guess we can do an LLC that specifies democratic board of directors. Open
to structures.

**Comment by rubinovitz** [comment]
I'd rather it be explicitly nonprofit given the history.

**Comment by brettneese** [comment]
You can be explicitly nonprofit without 501(c)3, we're not driving enough capital for a 501(c)3 status to matter.

**Comment by brettneese** [comment]
Not to mention the amount of upkeep involved with maintaining 501(c)3 status and the restrictions you have once you have that status.

**Comment by rubinovitz** [comment]
ok if you could point us in the direction of how to do that as not 5013c
nonprofit LLC that would be great

**Comment by brettneese** [comment]
We should create a separate issue for this, and a ton of it depends on
which state you incorporate in, but in New York State you'd start with
this hand guide:
http://www.dos.ny.gov/forms/corporations/1511-f-l_instructions.pdf

On Thursday, December 17, 2015, rubinovitz notifications@github.com wrote:

> ok if you could point us in the direction of how to do that as not 5013c
> nonprofit LLC that would be great
> 
> On Thu, Dec 17, 2015 at 5:33 PM, Brett Neese <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
> 
> > Not to mention the amount of upkeep involved with maintaining 501(c)3
> > status and the restrictions you have once you have that status.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/HackathonHackers/org/issues/4#issuecomment-165602308.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/HackathonHackers/org/issues/4#issuecomment-165603952.

## 

Brett Neese
563-210-3459

**Comment by rubinovitz** [comment]
I'd want @hellyeah 's confirmation of resignation before going through the
effort of creating a new legal entity.

**Comment by nsgomez** [comment]
@hellyeah @rhallie15 Any thoughts on the idea of placing HH under the control of a nonprofit holding organization like Hacker Fund?

**Comment by hallie** [comment]
@nsgomez I don't really see why not. I think having a board of some sort would also make a lot of sense.

**Comment by nsgomez** [comment]
I think the question is if we organize HH under an NPO, where does the board go? If it becomes its own legal entity then it would have its own board of directors with a president and its own bylaws, which would be simple. If we have Hacker Fund or some other group act as a holding company, though, I'm not entirely sure how that would work out.

**Comment by brettneese** [comment]
So it's like $75-100 and a couple weeks to incorporate a
nonprofit organization. (Though I'd recommend running your bylaws and
letter of incorporation by a real lawyer first.)

Even if you did want to use Hacker Fund's 501(c)3 status under an agreement
called a "fiscal sponsorship," you'd still want your own organization
underneath. (Fun fact: StudentRND was Hacker Fund's original fiscal sponsor
until they got their own 501(c)3.)

The thing to remember is that 501(c)3 is just a
classification/certification of a specific kind of nonprofit organization,
but the organization as a legal unit must exist in order to be granted
501(c)3 status as a public charity. (There are other 501(c)'s as well, such
as a 501(c)4 social welfare organization.)

Again I don't think we're moving around enough money for our tax
classification to matter too much and once we get to that discussion
there's a lot more work that needs to be done. I _think_ you need to
have  $5K before tax liability even comes into the picture.

But I'm still trying to think through the advantages we'd get as an
incorporated entity over an unicorporated one (what we currently are),
except maybe the ability to hold property? (like domain names, for
instance...)

On Friday, December 18, 2015, Nelson Gomez notifications@github.com wrote:

> I think the question is if we organize HH under an NPO, where does the
> board go? If it becomes its own legal entity then it would have its own
> board of directors with a president and its own bylaws, which would be
> simple. If we have Hacker Fund or some other group act as a holding
> company, though, I'm not entirely sure how that would work out.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/HackathonHackers/org/issues/4#issuecomment-165950026.

## 

Brett Neese
563-210-3459

**Comment by rubinovitz** [comment]
Yes, I'd be happy to retain counsel and then post the docs for the group to
give feedback on.
